
server:
  port: 8080

sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: sugarT
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token


    user-secret-key: sugarT
    user-ttl: 7200000
    user-token-name: authentication

  wechat:
    appid:
    secret:

    login-url: https://api.weixin.qq.com/sns/jscode2session


minio:
  endpoint:
#  endpoint: http://127.0.0.1:9000
  accessKey:
  secretKey:
  bucketName: sky-take-out


spring:
  main:
    allow-circular-references: true

  datasource:
    druid:
      # 空闲连接最大允许存活时间（调大到10分钟）
      min-evictable-idle-time-millis: 600000  # 10分钟
      max-evictable-idle-time-millis: 600000

      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/sky_take_out?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root=1024

      # 防止连接泄漏
      remove-abandoned: true
      remove-abandoned-timeout: 180  # 3分钟未关闭视为泄漏



  redis:
    host:
    port: 6379
    password: sugar=1099

mybatis-plus:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
#    日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info


